spring:
  #    配置数据源
  datasource:
#    url: jdbc:mysql://47.95.254.105:3306/lawyer?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/lawyer?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
server:
  port: 9342
  servlet:
    context-path: /lawyer
